// Code generated by protoc-gen-go.
// source: id.proto
// DO NOT EDIT!

package pbmsg

import proto "github.com/golang/protobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

// ------------------------------------------------------------------------------
// 消息id枚举定义
// ------------------------------------------------------------------------------
type EMsgId int32

const (
	// --------------------------------------------------------------------------
	// GM命令
	// --------------------------------------------------------------------------
	EMsgId_ID_NsError     EMsgId = 10000
	EMsgId_ID_NcGMCommand EMsgId = 10001
	EMsgId_ID_NsHeartbeat EMsgId = 10002
	// --------------------------------------------------------------------------
	// 登录[0-9]
	// --------------------------------------------------------------------------
	EMsgId_ID_NcLogin        EMsgId = 1
	EMsgId_ID_NsLogin        EMsgId = 2
	EMsgId_ID_NcCreatePlayer EMsgId = 3
	EMsgId_ID_NsCreatePlayer EMsgId = 4
)

var EMsgId_name = map[int32]string{
	10000: "ID_NsError",
	10001: "ID_NcGMCommand",
	10002: "ID_NsHeartbeat",
	1:     "ID_NcLogin",
	2:     "ID_NsLogin",
	3:     "ID_NcCreatePlayer",
	4:     "ID_NsCreatePlayer",
}
var EMsgId_value = map[string]int32{
	"ID_NsError":        10000,
	"ID_NcGMCommand":    10001,
	"ID_NsHeartbeat":    10002,
	"ID_NcLogin":        1,
	"ID_NsLogin":        2,
	"ID_NcCreatePlayer": 3,
	"ID_NsCreatePlayer": 4,
}

func (x EMsgId) Enum() *EMsgId {
	p := new(EMsgId)
	*p = x
	return p
}
func (x EMsgId) String() string {
	return proto.EnumName(EMsgId_name, int32(x))
}
func (x *EMsgId) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EMsgId_value, data, "EMsgId")
	if err != nil {
		return err
	}
	*x = EMsgId(value)
	return nil
}

func init() {
	proto.RegisterEnum("pbmsg.EMsgId", EMsgId_name, EMsgId_value)
}
