// Code generated by protoc-gen-go.
// source: logon.proto
// DO NOT EDIT!

package pbmsg

import proto "github.com/golang/protobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

// ----------------------------------------------------------------------------------------
// 消息 - 登陆
// ----------------------------------------------------------------------------------------
type NcLogin struct {
	AccId            *uint32 `protobuf:"varint,1,req,name=acc_id" json:"acc_id,omitempty"`
	Digest           *string `protobuf:"bytes,2,req,name=digest" json:"digest,omitempty"`
	Time             *uint32 `protobuf:"varint,3,req,name=time" json:"time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NcLogin) Reset()         { *m = NcLogin{} }
func (m *NcLogin) String() string { return proto.CompactTextString(m) }
func (*NcLogin) ProtoMessage()    {}

func (m *NcLogin) GetAccId() uint32 {
	if m != nil && m.AccId != nil {
		return *m.AccId
	}
	return 0
}

func (m *NcLogin) GetDigest() string {
	if m != nil && m.Digest != nil {
		return *m.Digest
	}
	return ""
}

func (m *NcLogin) GetTime() uint32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

type NsLogin struct {
	Error            *int32 `protobuf:"varint,1,req,name=error" json:"error,omitempty"`
	HasPlayer        *bool  `protobuf:"varint,2,opt,name=has_player" json:"has_player,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NsLogin) Reset()         { *m = NsLogin{} }
func (m *NsLogin) String() string { return proto.CompactTextString(m) }
func (*NsLogin) ProtoMessage()    {}

func (m *NsLogin) GetError() int32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return 0
}

func (m *NsLogin) GetHasPlayer() bool {
	if m != nil && m.HasPlayer != nil {
		return *m.HasPlayer
	}
	return false
}

// ------------------------------------------------------------------------------------------
// 消息 - 创建角色
// ------------------------------------------------------------------------------------------
type NcCreatePlayer struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	PlantIndex       *int32  `protobuf:"varint,2,req,name=plant_index" json:"plant_index,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NcCreatePlayer) Reset()         { *m = NcCreatePlayer{} }
func (m *NcCreatePlayer) String() string { return proto.CompactTextString(m) }
func (*NcCreatePlayer) ProtoMessage()    {}

func (m *NcCreatePlayer) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *NcCreatePlayer) GetPlantIndex() int32 {
	if m != nil && m.PlantIndex != nil {
		return *m.PlantIndex
	}
	return 0
}

type NsCreatePlayer struct {
	Error            *int32 `protobuf:"varint,1,req,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NsCreatePlayer) Reset()         { *m = NsCreatePlayer{} }
func (m *NsCreatePlayer) String() string { return proto.CompactTextString(m) }
func (*NsCreatePlayer) ProtoMessage()    {}

func (m *NsCreatePlayer) GetError() int32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return 0
}

func init() {
}
